@startuml
'https://plantuml.com/class-diagram
title 全局继承关系图 (Inheritance Hierarchy)

skinparam nodesep 40
skinparam ranksep 60

' ================================
' 飞行物体抽象父类
' ================================
abstract class AbstractFlyingObject {
    # locationX:int
    # locationY:int
    # speedX:int
    # speedY:int
    # image:BufferedImage
    # width:int
    # height:int
    # isValid:boolean

    + AbstractFlyingObject(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + crash(AbstractFlyingObject flyingObject):boolean
    + setLocation(double locationX, double locationY):void
    + getLocationX():int
    + getLocationY():int
    + getSpeedY():int
    + getImage():BufferedImage
    + getWidth():int
    + getHeight():int
    + notValid():boolean
    + vanish():void
}

' ================================
' 飞机类
' ================================
abstract class AbstractAircraft {
    # maxHp:int
    # hp:int
    # shootStrategy: ShootStrategy

    + AbstractAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + decreaseHp(int decrease):void
    + getHp():int
    + increaseHp(increase: int):void
    + shoot():List<BaseBullet>
    + setShootStrategy(shootStrategy: ShootStrategy): void
    + setShootNum(shootNum: int): void
 }
AbstractFlyingObject <|-- AbstractAircraft

' 1. 英雄机 (单例模式)
class HeroAircraft {
    - {static} instance: HeroAircraft
    - shootNum:int
    - power:int
    - direction:int

    ' 构造函数私有化
    - HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    ' 无参获取实例
    + {static} getInstance(): HeroAircraft
    + forward():void
}
AbstractAircraft <|-- HeroAircraft

' 2. 抽象敌机
abstract class AbstractEnemy {
    + AbstractEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + {abstract} getScore(): int
    + {abstract} dropProps(): List<AbstractProp>
}
AbstractAircraft <|-- AbstractEnemy

class MobEnemy {
    + MobEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + getScore(): int
    + dropProps(): List<AbstractProp>
}
AbstractEnemy <|-- MobEnemy

class EliteEnemy {
    + EliteEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + getScore(): int
    + dropProps(): List<AbstractProp>
}
AbstractEnemy <|-- EliteEnemy

class ElitePlusEnemy {
    + ElitePlusEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + getScore(): int
    + dropProps(): List<AbstractProp>
}
AbstractEnemy <|-- ElitePlusEnemy

class EliteProEnemy {
    + EliteProEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + getScore(): int
    + dropProps(): List<AbstractProp>
}
AbstractEnemy <|-- EliteProEnemy

class BossEnemy {
    + BossEnemy(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + getScore(): int
    + dropProps(): List<AbstractProp>
}
AbstractEnemy <|-- BossEnemy

' ==============================
' 子弹类
' ==============================
abstract class BaseBullet {
    - power:int
    + BaseBullet(int locationX, int locationY, int speedX, int speedY, int power)
    + forward():void
    + getPower():int
}
AbstractFlyingObject <|-- BaseBullet

class HeroBullet {
    + HeroBullet(int locationX, int locationY, int speedX, int speedY, int power)
}
BaseBullet <|-- HeroBullet

class EnemyBullet {
    + EnemyBullet(int locationX, int locationY, int speedX, int speedY, int power)
}
BaseBullet <|-- EnemyBullet


' ==============================
' 道具类
' ==============================
abstract class AbstractProp {
    + AbstractProp(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + {abstract} active(heroAircraft: HeroAircraft): void
}
AbstractFlyingObject <|-- AbstractProp

class BloodSupply {
    + BloodSupply(int locationX, int locationY, int speedX, int speedY)
    + active(heroAircraft: HeroAircraft): void
}
AbstractProp <|-- BloodSupply

class BulletSupply {
    + BulletSupply(int locationX, int locationY, int speedX, int speedY)
    + active(heroAircraft: HeroAircraft): void
}
AbstractProp <|-- BulletSupply

class BulletPlusSupply {
    + BulletPlusSupply(int locationX, int locationY, int speedX, int speedY)
    + active(heroAircraft: HeroAircraft): void
}
AbstractProp <|-- BulletPlusSupply

class BombSupply {
    + BombSupply(int locationX, int locationY, int speedX, int speedY)
    + active(heroAircraft: HeroAircraft): void
}
AbstractProp <|-- BombSupply

class FreezeSupply {
    + FreezeSupply(int locationX, int locationY, int speedX, int speedY)
    + active(heroAircraft: HeroAircraft): void
}
AbstractProp <|-- FreezeSupply

@enduml